apiVersion: v1
kind: Pod
metadata:
  name: test-irsa
  namespace: cert-manager
spec:
  serviceAccountName: cert-manager
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: ["sleep", "3600"]
